### ISSUE TITLE
devDependency

### ISSUE THREAD

**Issue by mixail-novikov** [Yankovsky/react-gtm-components#1]
https://github.com/Yankovsky/react-gtm-components/blob/5d26cf657b0e4e19ffdadee90ea25c4dbc1a2b3b/package.json#L8

react
react-dom
нужно в peerDependency добавить

текущие dependency переименовать в devDependency

и получается зависимостей у проекта нет👏

**Comment by Yankovsky** [comment]
react-dom тоже только dev зависимость. Сейчас сделаю.

**Comment by Yankovsky** [comment]
Поправлено в https://github.com/Yankovsky/react-gtm-components/commit/77b114614a9381a892f4fd3ea41346490728d296
